# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trap', models.BooleanField()),
                ('meme_lord', models.BooleanField()),
                ('higher_up', models.BooleanField()),
                ('name', models.CharField(max_length=32)),
                ('twitter', models.CharField(max_length=72)),
                ('description', models.TextField(max_length=140)),
            ],
        ),
    ]
